import { mysqlTable, varchar, text, int } from 'drizzle-orm/mysql-core';

export const processes = mysqlTable('processes', {
  id: varchar('id', { length: 255 }).primaryKey(),
  tenantId: varchar('tenantId', { length: 255 }).notNull(),
  responsibleDepartmentId: varchar('responsibleDepartmentId', { length: 255 }),
  vvtId: varchar('vvtId', { length: 255 }),
  process_type_id: varchar('process_type_id', { length: 255 }),
  emergencyProcessId: varchar('emergencyProcessId', { length: 255 }),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  inputs: text('inputs'),
  outputs: text('outputs'),
  kpis: text('kpis'),
  openQuestions: text('openQuestions'),
  status: varchar('status', { length: 50 }).default('draft'),
  ownerUserId: varchar('ownerUserId', { length: 255 }),
  ownerRoleId: varchar('ownerRoleId', { length: 255 }),
  currentVersion: int('currentVersion').default(1),
  publishedVersion: int('publishedVersion'),
  automationLevel: varchar('automationLevel', { length: 50 }),
  dataVolume: varchar('dataVolume', { length: 50 }),
  processingFrequency: varchar('processingFrequency', { length: 50 }),
  createdAt: varchar('createdAt', { length: 50 }),
  updatedAt: varchar('updatedAt', { length: 50 }),
  tags: text('tags'),
});
