CREATE TABLE `processes` (
	`id` varchar(255) NOT NULL,
	`tenantId` varchar(255) NOT NULL,
	`responsibleDepartmentId` varchar(255),
	`vvtId` varchar(255),
	`process_type_id` varchar(255),
	`emergencyProcessId` varchar(255),
	`title` varchar(255) NOT NULL,
	`description` text,
	`inputs` text,
	`outputs` text,
	`kpis` text,
	`openQuestions` text,
	`status` varchar(50) DEFAULT 'draft',
	`ownerUserId` varchar(255),
	`ownerRoleId` varchar(255),
	`currentVersion` int DEFAULT 1,
	`publishedVersion` int,
	`automationLevel` varchar(50),
	`dataVolume` varchar(50),
	`processingFrequency` varchar(50),
	`createdAt` varchar(50),
	`updatedAt` varchar(50),
	`tags` text,
	CONSTRAINT `processes_id` PRIMARY KEY(`id`)
);
